<?php

use Illuminate\Database\Seeder;
use App\Buku;
use Carbon\Carbon;

class BukuTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      App\Buku::insert([
      [
          'isbn' => '978-602-1371-17-6',
          'judul' => 'Berguru di Negeri Jepang',
          'slug' => str_slug('Berguru di Negeri Jepang', $separator = '-'),
          'pengarang' => 'Ignasius Seda',
          'penerbit' => 'AG Publishing',
          'halaman' => '43',
          'stok' => 5,
          'image' => 'bahasa-jepang.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-364-209-0',
          'judul' => 'Belajar Bahasa Jepang',
          'slug' => str_slug('Belajar Bahasa Jepang', $separator = '-'),
          'pengarang' => 'Arlin Muhardika',
          'penerbit' => '	Goresan Pena',
          'halaman' => '	56',
          'stok' => 5,
          'image' => 'belajar-jepang.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-17817-2-2',
          'judul' => 'Blender Untuk Pemula',
          'slug' => str_slug('Blender Untuk Pemula', $separator = '-'),
          'pengarang' => 'Ahmad Budi Ahda',
          'penerbit' => 'Abda Publisher',
          'halaman' => '78',
          'stok' => 5,
          'image' => 'belajar-blender.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-7847-10-1',
          'judul' => "Let's know English",
          'slug' => str_slug("Let's know English", $separator = '-'),
          'pengarang' => 'Alby S',
          'penerbit' => '3M Media Karya',
          'halaman' => '213',
          'stok' => 5,
          'image' => 'belajar-inggris.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-14341-9-2',
          'judul' => 'Mudah Belajar Java',
          'slug' => str_slug('Mudah Belajar Java', $separator = '-'),
          'pengarang' => 'N. Syamsuddin',
          'penerbit' => 'Akarpadi Selaras Media',
          'halaman' => '111',
          'stok' => 5,
          'image' => 'belajar-java.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-6280-70-1',
          'judul' => 'Belajar Mikrokontroller',
          'slug' => str_slug('Belajar Mikrokontroller', $separator = '-'),
          'pengarang' => 'Nasrullah',
          'penerbit' => 'Cahaya Pena',
          'halaman' => '102',
          'stok' => 5,
          'image' => 'belajar-mikrokontroler.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-336-421-3',
          'judul' => 'Belajar Web dengan PHP dan MySQL',
          'slug' => str_slug('Belajar Web dengan PHP dan MySQL', $separator = '-'),
          'pengarang' => 'Misbahuddin Hasan',
          'penerbit' => 'CV. Diandra Kreatif',
          'halaman' => '152',
          'stok' => 5,
          'image' => 'belajar-mysql.png',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-7709-19-5',
          'judul' => 'Beginning Blender',
          'slug' => str_slug('Beginning Blender', $separator = '-'),
          'pengarang' => 'Mufidun Alamin',
          'penerbit' => 'Absolute Media',
          'halaman' => '121',
          'stok' => 5,
          'image' => 'blender.png',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-1648-02-5',
          'judul' => 'English on Sky 1',
          'slug' => str_slug('English on Sky 1', $separator = '-'),
          'pengarang' => 'Kamalasari',
          'penerbit' => 'Adicita Karya Nusa',
          'halaman' => '122',
          'stok' => 5,
          'image' => 'english.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-6325-40-2',
          'judul' => 'HTML5 dan PHP',
          'slug' => str_slug('HTML5 dan PHP', $separator = '-'),
          'pengarang' => 'Eka Suswanti',
          'penerbit' => 'AE Publishing',
          'halaman' => '162',
          'stok' => 5,
          'image' => 'html5-dan-php.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-6325-78-5',
          'judul' => 'Intermediate Phyton',
          'slug' => str_slug('Intermediate Phyton', $separator = '-'),
          'pengarang' => 'Muhammad Machfudzi ',
          'penerbit' => 'AE Publishing',
          'halaman' => '122',
          'stok' => 5,
          'image' => 'intermediate-phyton.png',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-6325-89-1',
          'judul' => 'Komputasi Numerik',
          'slug' => str_slug('Komputasi Numerik', $separator = '-'),
          'pengarang' => 'Evan Ardiansyah ',
          'penerbit' => 'AE Publishing',
          'halaman' => '124',
          'stok' => 5,
          'image' => 'komputasi-numerik.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-6325-97-6',
          'judul' => 'Belajar Komputer',
          'slug' => str_slug('Belajar Komputer', $separator = '-'),
          'pengarang' => 'Wulan Tiwi',
          'penerbit' => 'Media',
          'halaman' => '126',
          'stok' => 5,
          'image' => 'komputer.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-7748-78-1',
          'judul' => 'Linux untuk Pemula',
          'slug' => str_slug('Linux untuk Pemula', $separator = '-'),
          'pengarang' => 'Rizki Fitria Harini',
          'penerbit' => 'AE Publishing',
          'halaman' => '312',
          'stok' => 5,
          'image' => 'linux.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-9055-19-1',
          'judul' => 'Komputasi Numerik dengan Matlab',
          'slug' => str_slug('Komputasi Numerik dengan Matlab', $separator = '-'),
          'pengarang' => 'Asma Nadia ',
          'penerbit' => 'PT. Mata Hati Isa Asmanadia',
          'halaman' => '412',
          'stok' => 5,
          'image' => 'matlab.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-9055-42-9',
          'judul' => 'Organisasi dan Arsitektur Komputer',
          'slug' => str_slug('Organisasi dan Arsitektur Komputer', $separator = '-'),
          'pengarang' => 'Asma Nadia',
          'penerbit' => 'Asma Nadia Publishing House',
          'halaman' => '122',
          'stok' => 5,
          'image' => 'mikro.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-9055-22-1',
          'judul' => 'Mikrokontroller Konsep Dasar dan Praktis',
          'slug' => str_slug('Mikrokontroller Konsep Dasar dan Praktis', $separator = '-'),
          'pengarang' => 'Fahmi',
          'penerbit' => 'Media',
          'halaman' => '122',
          'stok' => 5,
          'image' => 'mikrokontroller.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-1363-06-5',
          'judul' => 'Buku Pintar Menguasai PHP dan MySQL',
          'slug' => str_slug('Buku Pintar Menguasai PHP dan MySQL', $separator = '-'),
          'pengarang' => 'Mohammad Thobib',
          'penerbit' => 'Asrifa (CV)',
          'halaman' => '122',
          'stok' => 5,
          'image' => 'mysql.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-270-079-1',
          'judul' => 'Teknik Pemrograman Pascal',
          'slug' => str_slug('Teknik Pemrograman Pascal', $separator = '-'),
          'pengarang' => 'Hanjaeli',
          'penerbit' => 'Aranca Pratama',
          'halaman' => '122',
          'stok' => 5,
          'image' => 'pascal.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-18849-8-0',
          'judul' => 'Kreasi Photoshop CS3',
          'slug' => str_slug('Kreasi Photoshop CS3', $separator = '-'),
          'pengarang' => 'Angga Reza',
          'penerbit' => 'CV. Bumen Pustaka Emas',
          'halaman' => '315',
          'stok' => 5,
          'image' => 'photoshop-cs3.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-979-8559-89-2',
          'judul' => 'Belajar Photoshop CS5',
          'slug' => str_slug('Belajar Photoshop CS5', $separator = '-'),
          'pengarang' => 'Ismawandi',
          'penerbit' => 'Media',
          'halaman' => '122',
          'stok' => 5,
          'image' => 'photoshop-cs5.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-6580-06-1',
          'judul' => 'PHP Komplet',
          'slug' => str_slug('PHP Komplet', $separator = '-'),
          'pengarang' => 'Fahmi',
          'penerbit' => 'Adi Buana ',
          'halaman' => '312',
          'stok' => 5,
          'image' => 'php-komplet.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-1648-98-8',
          'judul' => 'Pintar Bahasa Jepang Super Lengkap',
          'slug' => str_slug('Pintar Bahasa Jepang Super Lengkap', $separator = '-'),
          'pengarang' => 'Fahmi',
          'penerbit' => 'Media',
          'halaman' => '152',
          'stok' => 5,
          'image' => 'pintar-jepang.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-979-016-775-9',
          'judul' => 'Pro Android',
          'slug' => str_slug('Pro Android', $separator = '-'),
          'pengarang' => 'Kili Astarani',
          'penerbit' => 'Adjie Media Nusantara',
          'halaman' => '121',
          'stok' => 5,
          'image' => 'pro-android.PNG',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
      [
          'isbn' => '978-602-1371-60-2',
          'judul' => 'Ilmu Pengantar Telekomunikasi',
          'slug' => str_slug('Ilmu Pengantar Telekomunikasi', $separator = '-'),
          'pengarang' => 'Fadhilatul Hasnah',
          'penerbit' => 'AG Publishing',
          'halaman' => '134',
          'stok' => 5,
          'image' => 'telekomunikasi.jpg',
          'created_at' => \Carbon\Carbon::now('Asia/Jakarta'),
      ],
    ]);
    }
}
